"""initial tables

Revision ID: a1f4d10cb9c0
Revises:

Create Date: 2026-09-15 01:35:06.618479
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1f4d10cb9c0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("leetcode", "codeforces", name="source"),
            nullable=False,
        ),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("url", sa.String(500), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="difficulty"),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )

    op.create_index(
        op.f("ix_questions_id"),
        "questions",
        ["id"],
        unique=False,
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "year",
            sa.Enum(
                "first",
                "second",
                "third",
                "final",
                "working",
                name="year",
            ),
            nullable=False,
        ),
        sa.Column(
            "org_type",
            sa.Enum(
                "service",
                "product",
                "toptech",
                "hft",
                name="org_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum(
                "beginner",
                "intermediate",
                "pro",
                name="level",
            ),
            nullable=False,
        ),
        sa.Column("trial_start", sa.Date(), nullable=True),
        sa.Column("subscription_end", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "trial",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )

    op.create_index(
        op.f("ix_users_id"),
        "users",
        ["id"],
        unique=False,
    )

    op.create_table(
        "daily_question_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket_key", sa.String(100), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column(
            "slot",
            sa.Enum("morning", "evening", name="slot"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_daily_question_log_id"),
        "daily_question_log",
        ["id"],
        unique=False,
    )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stars_amount", sa.Integer(), nullable=True),
        sa.Column("paid_at", sa.Date(), nullable=True),
        sa.Column("valid_till", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_payments_id"),
        "payments",
        ["id"],
        unique=False,
    )

    op.create_table(
        "user_question_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("send_at", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "solved",
                "skipped",
                name="log_status",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_user_question_log_id"),
        "user_question_log",
        ["id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_user_question_log_id"),
        table_name="user_question_log",
    )
    op.drop_table("user_question_log")

    op.drop_index(
        op.f("ix_payments_id"),
        table_name="payments",
    )
    op.drop_table("payments")

    op.drop_index(
        op.f("ix_daily_question_log_id"),
        table_name="daily_question_log",
    )
    op.drop_table("daily_question_log")

    op.drop_index(
        op.f("ix_users_id"),
        table_name="users",
    )
    op.drop_table("users")

    op.drop_index(
        op.f("ix_questions_id"),
        table_name="questions",
    )
    op.drop_table("questions")

    # ### end Alembic commands ###